version: "3.8"

services:
  db:
    image: postgres:16
    container_name: devopsdemo-db
    restart: always
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: devopsdemo-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

volumes:
  postgres_data: